theme: jekyll-theme-slate
title: Matthew Lee
description: Major-BS Computer Science  
 ! [alt text] (https://www.insidehighered.com/sites/default/server_files/styles/large-copy/public/media/snhu-online-degree-cost-768x509.jpg?itok=59O59oBU)
